displays:
- camId: '1'
  camera_name: MacBook Pro Camera (Device 1)
  corners:
  - x: 301.6104404784715
    y: 94.05571182864458
  - x: 601.6104404784716
    y: 94.05571182864458
  - x: 601.1150831308586
    y: 364.21074909420184
  - x: 301.1150831308586
    y: 364.21074909420184
  enablePerspective: false
  h: 270.15503726555727
  id: disp_1766833702891
  name: hp_webcam
  rotation: 0
  w: 300.495357347613
  x: 301.1150831308586
  y: 94.05571182864458
- camId: '0'
  camera_name: HP 320 FHD Webcam (Device 0)
  corners:
  - x: 187.6782505274925
    y: 140.12394515664914
  - x: 487.67825052749254
    y: 140.12394515664914
  - x: 487.67825052749254
    y: 398.3904060794955
  - x: 187.6782505274925
    y: 398.3904060794955
  enablePerspective: false
  h: 258.26646092284636
  id: disp_1766833720487
  name: macbookCam
  rotation: 0
  w: 300
  x: 187.6782505274925
  y: 140.12394515664914
- camId: '0'
  camera_name: HP 320 FHD Webcam (Device 0)
  corners:
  - x: 28.173184596121942
    y: 218.39040607949553
  - x: 598.6382963927939
    y: 217.89504873188258
  - x: 596.1615096547291
    y: 312.6935849424549
  - x: 25.696397858057182
    y: 313.1889422900678
  enablePerspective: false
  h: 95.29389355818523
  id: disp_1766838281748
  name: macbook_wide
  rotation: 0
  w: 572.9418985347368
  x: 25.696397858057182
  y: 217.89504873188258
- camId: '0'
  camera_name: HP 320 FHD Webcam (Device 0)
  corners:
  - x: 270.4029275788555
    y: 99.0092853047741
  - x: 400
    y: 100
  - x: 394.5510691762575
    y: 466.74972005008294
  - x: 264.953996755113
    y: 465.7590053548571
  enablePerspective: false
  h: 367.74043474530885
  id: disp_1766838301335
  name: macbookHigh
  rotation: 0
  w: 135.046003244887
  x: 264.953996755113
  y: 99.0092853047741
- camId: '1'
  camera_name: MacBook Pro Camera (Device 1)
  corners:
  - x: 108.91643225703314
    y: 147.5543053708434
  - x: 624.3968784686673
    y: 146.5635906756175
  - x: 623.4061637734414
    y: 263.15785018115963
  - x: 107.92571756180723
    y: 264.14856487638554
  enablePerspective: false
  h: 117.58497420076804
  id: disp_1766838325637
  name: hp_webcam_wide
  rotation: 0
  w: 516.4711609068601
  x: 107.92571756180723
  y: 146.5635906756175
- camId: '1'
  camera_name: MacBook Pro Camera (Device 1)
  corners:
  - x: 390.2794057011899
    y: 27.67782724850899
  - x: 521.8579075127861
    y: 28.173184596121942
  - x: 520.8671928175603
    y: 468.2357920929219
  - x: 389.288691005964
    y: 467.7404347453089
  enablePerspective: false
  h: 440.5579648444129
  id: disp_1766838346448
  name: hp_webcam_high
  rotation: 0
  w: 132.56921650682216
  x: 389.288691005964
  y: 27.67782724850899
