displays:
- camId: '1'
  camera_name: MacBook Pro Camera (Device 1)
  corners:
  - x: 220.94682884088664
    y: 117.52033501900695
  - x: 444.08342359621105
    y: 114.12930243468304
  - x: 444.08342359621105
    y: 382.296149627105
  - x: 220.94682884088664
    y: 385.687182211429
  enablePerspective: false
  h: 271.55787977674595
  hardware_id: 6C707041-05AC-0010-0008-000000000001
  id: disp_1766864068949
  name: macbook_cam1
  rotation: 0
  w: 223.1365947553244
  x: 220.94682884088664
  y: 114.12930243468304
- camId: '0'
  camera_name: HP 320 FHD Webcam (Device 0)
  corners:
  - x: 120.34619550594356
    y: 116.95516292161963
  - x: 420.34619550594357
    y: 116.95516292161963
  - x: 422.04171179810555
    y: 465.9416200404286
  - x: 122.04171179810552
    y: 465.9416200404286
  enablePerspective: false
  h: 348.98645711880897
  hardware_id: '0x210000003f0654a'
  id: disp_1766864109344
  name: hpcam1
  rotation: 0
  w: 301.695516292162
  x: 120.34619550594356
  y: 116.95516292161963
- camId: '1'
  camera_name: MacBook Pro Camera (Device 1)
  corners:
  - x: 58.17726479333826
    y: 173.4723726603517
  - x: 578.0292106770061
    y: 171.21168427080244
  - x: 578.0292106770061
    y: 351.21168427080244
  - x: 58.17726479333826
    y: 353.4723726603517
  enablePerspective: false
  h: 182.26068838954927
  hardware_id: 6C707041-05AC-0010-0008-000000000001
  id: disp_1766864185481
  name: macbook_wide
  rotation: 0
  w: 519.8519458836678
  x: 58.17726479333826
  y: 171.21168427080244
- camId: '1'
  camera_name: MacBook Pro Camera (Device 1)
  corners:
  - x: 249.77060580764
    y: 40.091757676943985
  - x: 396.04379531828874
    y: 36.70072509262006
  - x: 400
    y: 469.3326526247525
  - x: 253.72681048935127
    y: 472.7236852090764
  enablePerspective: false
  h: 436.0229601164563
  hardware_id: 6C707041-05AC-0010-0008-000000000001
  id: disp_1766864204451
  name: macbook_long
  rotation: 0
  w: 150.22939419236
  x: 249.77060580764
  y: 36.70072509262006
- camId: '0'
  camera_name: HP 320 FHD Webcam (Device 0)
  corners:
  - x: 45.17830655342988
    y: 213.5995915748515
  - x: 575.7685222874568
    y: 218.6861404513374
  - x: 575.7685222874568
    y: 398.6861404513374
  - x: 45.17830655342988
    y: 393.5995915748515
  enablePerspective: false
  h: 185.0865488764859
  hardware_id: '0x210000003f0654a'
  id: disp_1766864223180
  name: hp_wide
  rotation: 0
  w: 530.590215734027
  x: 45.17830655342988
  y: 213.5995915748515
- camId: '0'
  camera_name: HP 320 FHD Webcam (Device 0)
  corners:
  - x: 182.51512621854883
    y: 80.7841486888311
  - x: 352.52554381946504
    y: 80.7841486888311
  - x: 349.6996833325284
    y: 477.8102340855623
  - x: 179.68926573161224
    y: 477.8102340855623
  enablePerspective: false
  h: 397.0260853967312
  hardware_id: '0x210000003f0654a'
  id: disp_1766864234904
  name: hp_long
  rotation: 0
  w: 172.8362780878528
  x: 179.68926573161224
  y: 80.7841486888311
- camId: '0'
  camera_name: HP 320 FHD Webcam (Device 0)
  corners:
  - x: 92.0875906365775
    y: 280.28989906655534
  - x: 234.404575465515
    y: 298.9405782803369
  - x: 200.49424962227573
    y: 417.3368196651189
  - x: 53.655888014239686
    y: 386.8175264062036
  enablePerspective: true
  h: 137.0469205985636
  hardware_id: '0x210000003f0654a'
  id: disp_1766888538042
  name: screen
  rotation: 0
  w: 180.74868745127532
  x: 53.655888014239686
  y: 280.28989906655534
