displays:
- camId: '1'
  camera_name: Host Camera 1
  corners:
  - x: 159.44288171355424
    y: 90.58821039535391
  - x: 504.0250429987199
    y: 91.57892509057982
  - x: 509.96933117007535
    y: 416.22327059356184
  - x: 165.38716988490967
    y: 415.23255589833593
  enablePerspective: false
  h: 325.63506019820795
  id: disp_1766825597113
  name: hpwebcam
  rotation: 0
  w: 350.5264494565211
  x: 159.44288171355424
  y: 90.58821039535391
- camId: '0'
  camera_name: Host Camera 0
  corners:
  - x: 184.70610644181482
    y: 122.7864379901958
  - x: 484.70610644181477
    y: 122.7864379901958
  - x: 487.18289317987956
    y: 453.3750716645332
  - x: 187.18289317987958
    y: 453.3750716645332
  enablePerspective: false
  h: 330.5886336743374
  id: disp_1766825622387
  name: macbook_cam
  rotation: 0
  w: 302.47678673806473
  x: 184.70610644181482
  y: 122.7864379901958
- camId: '1'
  camera_name: Host Camera 1
  corners:
  - x: 250.0932763267245
    y: 57.89462545289907
  - x: 445.5728759803916
    y: 57.39926810528612
  - x: 452.507878846973
    y: 468.2357920929218
  - x: 257.0282791933058
    y: 468.73114944053475
  enablePerspective: false
  h: 411.3318813352486
  id: disp_1766825767061
  name: high_image_hpwebcam
  rotation: 0
  w: 202.41460252024848
  x: 250.0932763267245
  y: 57.39926810528612
- camId: '1'
  camera_name: Host Camera 1
  corners:
  - x: 14.798536210572237
    y: 136.1610863757455
  - x: 642.2297429827337
    y: 134.1796569852937
  - x: 640.2483135922819
    y: 283.9628587809036
  - x: 12.81710682012043
    y: 285.9442881713554
  enablePerspective: false
  h: 151.76463118606173
  id: disp_1766825858149
  name: wide_image_hpwebcam
  rotation: 0
  w: 629.4126361626132
  x: 12.81710682012043
  y: 134.1796569852937
- camId: '0'
  camera_name: Host Camera 0
  corners:
  - x: 0.4331731297966144
    y: 163.40574049445786
  - x: 638.26688420183
    y: 159.44288171355424
  - x: 638.26688420183
    y: 339.44288171355424
  - x: 0.4331731297966144
    y: 343.40574049445786
  enablePerspective: false
  h: 183.96285878090362
  id: disp_1766825884401
  name: wide_image_macbook_cam
  rotation: 0
  w: 637.8337110720333
  x: 0.4331731297966144
  y: 159.44288171355424
- camId: '0'
  camera_name: Host Camera 0
  corners:
  - x: 251.08399102195037
    y: 13.312464167733381
  - x: 392.5696397858057
    y: 10.340320082055669
  - x: 404.9535734761295
    y: 469.22650678814773
  - x: 263.46792471227417
    y: 472.19865087382544
  enablePerspective: false
  h: 461.8583307917698
  id: disp_1766825908592
  name: high_image_macbook_webcam
  rotation: 0
  w: 153.86958245417915
  x: 251.08399102195037
  y: 10.340320082055669
