cameras:
  '0x210000003f0654a':
    resolution: 1920x1080
  6C707041-05AC-0010-0008-000000000001:
    resolution: 1920x1080
displays:
- camId: '1'
  camera_name: MacBook Pro Camera (Device 1)
  corners:
  - x: 777.0761726700104
    y: 253.16163839196398
  - x: 1196.8926573161227
    y: 249.77060580764007
  - x: 1200.2836899004467
    y: 858.7362277246166
  - x: 780.4672052543343
    y: 862.1272603089405
  enablePerspective: false
  h: 612.3566545013005
  hardware_id: 6C707041-05AC-0010-0008-000000000001
  id: disp_1766864068949
  name: macbook_cam1
  rotation: 0
  w: 423.20751723043634
  x: 777.0761726700104
  y: 249.77060580764007
- camId: '1'
  camera_name: MacBook Pro Camera (Device 1)
  corners:
  - x: 41.222101871718635
    y: 439.66843052977987
  - x: 1873.4036578887456
    y: 439.1032584323926
  - x: 1876.7946904730695
    y: 758.1355943896734
  - x: 44.61313445604256
    y: 758.7007664870608
  enablePerspective: false
  h: 319.59750805466825
  hardware_id: 6C707041-05AC-0010-0008-000000000001
  id: disp_1766864185481
  name: macbook_wide
  rotation: 0
  w: 1835.5725886013508
  x: 41.222101871718635
  y: 439.1032584323926
- camId: '1'
  camera_name: MacBook Pro Camera (Device 1)
  corners:
  - x: 804.2044333446017
    y: 46.87382284559183
  - x: 1187.849903757925
    y: 35.00520880045808
  - x: 1190.1105921474743
    y: 1055.9812897127915
  - x: 806.465121734151
    y: 1067.8499037579252
  enablePerspective: false
  h: 1032.844694957467
  hardware_id: 6C707041-05AC-0010-0008-000000000001
  id: disp_1766864204451
  name: macbook_long
  rotation: 0
  w: 385.9061588028726
  x: 804.2044333446017
  y: 35.00520880045808
- camId: '0'
  camera_name: HP 320 FHD Webcam (Device 0)
  corners:
  - x: 1213.4084322177075
    y: 306.8254106973006
  - x: 1854.2362550115056
    y: 360.44145058098997
  - x: 1724.743995911195
    y: 853.112083697202
  - x: 1090.6982382860447
    y: 684.2009359464994
  enablePerspective: true
  h: 546.2866729999014
  hardware_id: '0x210000003f0654a'
  id: disp_1766996474213
  name: hpDisplay
  rotation: 15
  w: 763.5380167254609
  x: 1090.6982382860447
  y: 306.8254106973006
- camId: '0'
  camera_name: HP 320 FHD Webcam (Device 0)
  corners:
  - x: 1073.2263517009665
    y: 693.430702256687
  - x: 1727.5892567628168
    y: 771.4244516961373
  - x: 1549.5600460858107
    y: 963.293065741271
  - x: 969.7998578790866
    y: 878.5172511331729
  enablePerspective: true
  h: 269.86236348458397
  hardware_id: '0x210000003f0654a'
  id: disp_1766997883666
  name: keyboard
  rotation: 0
  w: 757.7893988837302
  x: 969.7998578790866
  y: 693.430702256687
