displays:
- camId: '0'
  camera_name: MacBook Pro Camera (Device 0)
  corners:
  - x: 160.92895375639313
    y: 82.16713548593373
  - x: 460.9289537563931
    y: 82.16713548593373
  - x: 460.9289537563931
    y: 430.0932763267245
  - x: 160.92895375639313
    y: 430.0932763267245
  enablePerspective: false
  h: 347.92614084079077
  id: disp_1766840019382
  name: macbook_webcam
  rotation: 0
  w: 300
  x: 160.92895375639313
  y: 82.16713548593373
- camId: '0'
  camera_name: MacBook Pro Camera (Device 0)
  corners:
  - x: 33.12675807225146
    y: 100
  - x: 629.8458092924097
    y: 98.51392795716114
  - x: 629.8458092924097
    y: 278.5139279571611
  - x: 33.12675807225146
    y: 280
  enablePerspective: false
  h: 181.48607204283886
  id: disp_1766840039657
  name: wide_macbook_webcam
  rotation: 0
  w: 596.7190512201582
  x: 33.12675807225146
  y: 98.51392795716114
- camId: '0'
  camera_name: MacBook Pro Camera (Device 0)
  corners:
  - x: 249.1025616314986
    y: 23.714968467605374
  - x: 401.9814293904518
    y: 19.752109686701758
  - x: 405.9442881713554
    y: 468.2357920929218
  - x: 253.0654204124022
    y: 472.19865087382544
  enablePerspective: false
  h: 452.44654118712367
  id: disp_1766840059178
  name: long_macbook_cam
  rotation: 0
  w: 156.84172653985684
  x: 249.1025616314986
  y: 19.752109686701758
- camId: '1'
  camera_name: HP 320 FHD Webcam (Device 1)
  corners:
  - x: 413.5612010389987
    y: 134.1796569852937
  - x: 636.7808121589911
    y: 132.69358494245483
  - x: 636.7808121589911
    y: 312.69358494245483
  - x: 413.5612010389987
    y: 314.1796569852937
  enablePerspective: false
  h: 181.48607204283888
  id: disp_1766840086720
  name: hp_webcam
  rotation: 0
  w: 223.2196111199924
  x: 413.5612010389987
  y: 132.69358494245483
- camId: '1'
  camera_name: HP 320 FHD Webcam (Device 1)
  corners:
  - x: 15.29389355818519
    y: 158.9475243659413
  - x: 639.2575988970558
    y: 155.48002293265063
  - x: 637.771526854217
    y: 296.84214981884037
  - x: 13.807821515346333
    y: 300.30965125213106
  enablePerspective: false
  h: 144.82962831948043
  id: disp_1766840102795
  name: long_hp_webcam
  rotation: 0
  w: 625.4497773817095
  x: 13.807821515346333
  y: 155.48002293265063
- camId: '1'
  camera_name: HP 320 FHD Webcam (Device 1)
  corners:
  - x: 448.23621537190536
    y: 33.622115419864414
  - x: 627.3690225543451
    y: 29.16389929134785
  - x: 626.8736652067321
    y: 459.8147171835016
  - x: 447.7408580242924
    y: 464.2729333120182
  enablePerspective: false
  h: 435.1090340206704
  id: disp_1766840125848
  name: high_ho_webcam
  rotation: 0
  w: 179.6281645300527
  x: 447.7408580242924
  y: 29.16389929134785
