displays:
- camId: fd871e4004fa10ff084e7b2405965ac09bd633c4ecabafdee4f5eeb8ffcb9f9a
  camera_name: MacBook Pro Camera (0000:0001)
  corners:
  - x: 205.8785313965458
    y: 224.61809447558045
  - x: 505.8785313965458
    y: 224.61809447558045
  - x: 505.8785313965458
    y: 404.61809447558045
  - x: 205.8785313965458
    y: 404.61809447558045
  enablePerspective: false
  h: 180
  id: disp_1766728273094
  name: Display1
  rotation: 0
  w: 300
  x: 205.8785313965458
  y: 224.61809447558045
- camId: fd871e4004fa10ff084e7b2405965ac09bd633c4ecabafdee4f5eeb8ffcb9f9a
  camera_name: MacBook Pro Camera (0000:0001)
  corners:
  - x: 191.56355284004516
    y: 69.3330933956486
  - x: 471.8809018763484
    y: 176.20771072483177
  - x: 407.7561314788386
    y: 344.39812014661373
  - x: 127.43878244253526
    y: 237.52350281743054
  enablePerspective: true
  h: 275.0650267509651
  id: disp_1766728380598
  name: Display2
  rotation: 20
  w: 344.4421194338131
  x: 127.43878244253526
  y: 69.3330933956486
- camId: fd871e4004fa10ff084e7b2405965ac09bd633c4ecabafdee4f5eeb8ffcb9f9a
  camera_name: MacBook Pro Camera (0000:0001)
  corners:
  - x: 265.03025243709766
    y: 100
  - x: 432.21480955107734
    y: 96.60896741567606
  - x: 433.9103258432394
    y: 472.72368520907645
  - x: 266.72576872925964
    y: 476.1147177934003
  enablePerspective: false
  h: 379.5057503777242
  id: disp_1766728563733
  name: high Display
  rotation: 0
  w: 168.88007340614172
  x: 265.03025243709766
  y: 96.60896741567606
- camId: fd871e4004fa10ff084e7b2405965ac09bd633c4ecabafdee4f5eeb8ffcb9f9a
  camera_name: MacBook Pro Camera (0000:0001)
  corners:
  - x: 40.09175767694399
    y: 246.94474532070345
  - x: 615.3305691045691
    y: 241.29302434683024
  - x: 616.4609132993438
    y: 386.25235430881634
  - x: 41.222101871718635
    y: 391.9040752826895
  enablePerspective: false
  h: 150.61105093585928
  id: disp_1766728621226
  name: wide Display
  rotation: 0
  w: 576.3691556223998
  x: 40.09175767694399
  y: 241.29302434683024
- camId: fd871e4004fa10ff084e7b2405965ac09bd633c4ecabafdee4f5eeb8ffcb9f9a
  camera_name: MacBook Pro Camera (0000:0001)
  corners:
  - x: 195.51408445845723
    y: 251.466122099802
  - x: 495.5140844584572
    y: 251.466122099802
  - x: 490.42753558197137
    y: 333.12617715440814
  - x: 190.42753558197134
    y: 333.12617715440814
  enablePerspective: false
  h: 81.66005505460615
  id: disp_1766731687711
  name: New Display
  rotation: 0
  w: 305.08654887648584
  x: 190.42753558197134
  y: 251.466122099802
